name: "PiSwitch"
version: "0.2.2"
slug: "piswitch"
description: "IoT switch controller"
arch:
  - aarch64
startup: "application"
boot: "auto"
init: false

map:
  - config:rw

panel_icon: "mdi:toggle-switch"
panel_title: "PiSwitch"
panel_admin: false

ingress: true
ingress_port: 8099
ingress_entry: "/"
ingress_stream: true

options:
  mqtt_broker: ""
  mqtt_username: ""
  mqtt_password: ""
  mqtt_client_id: "piswitch-ha"
schema:
  mqtt_broker: "str"
  mqtt_username: "str"
  mqtt_password: "password"
  mqtt_client_id: "str"

image: "maex-amd-1.fritz.box:4450/piswitch/piswitch3app-ha-{arch}"

watchdog: "http://[HOST]:[PORT:8099]/"