name: "PiSwitch"
version: "0.2.26"
slug: "piswitch"
description: "IoT switch controller"
arch:
  - aarch64
startup: "application"
boot: "auto"
init: false

map:
  - addon_config:rw

panel_icon: "mdi:toggle-switch"
panel_title: "PiSwitch"
panel_admin: false

ingress: true
ingress_port: 8099
ingress_entry: ""
ingress_stream: true

options:
  mqtt_broker: "tcp://core-mosquitto:1883"
  mqtt_username: ""
  mqtt_password: ""
  mqtt_client_id: "piswitch-ha"
  timeout: 10
schema:
  mqtt_broker: "str"
  mqtt_username: "str"
  mqtt_password: "password"
  mqtt_client_id: "str"
  timeout: "int"

image:  "ghcr.io/ickeundso/piswitch3app-ha-{arch}"

watchdog: "http://[HOST]:[PORT:8099]/"
